### PR TITLE
Homepage UI

### PR DESCRIPTION
**Pull request by surajaswal-29**
1. Complete HomePage UI with responsiveness as Per Figma Design
2. Created an Ellipse Component for background design
3. Created Mobile Navbar drawer from top using MUI Drawer

package used

- MUI (for various  built in features and components)
- Lucide React (Icons)

Desktop View (1100px above screens)
image

Mobile View (600px less than screen)
image

Tablet View (768px above)
image

### CODE REVIEW

**Review by abhishekpandit5599 — CHANGES_REQUESTED** [review]
1. Use Container, for reference you can check dmail.ai with ctrl -. 
Screenshot from 2024-04-12 10-45-44

2. use amination in 'How it Works' section according to figma
3. Use animation on Hero section dollar price - increment counting animation 
Screenshot from 2024-04-12 10-46-12

**Comment by surajaswal-29** [comment]
Fixes has been done and animation applied to various components

**Comment by abhishekpandit5599** [comment]
1. The footer is not wrapped in a container
2. Market cards are break 
Screenshot from 2024-04-18 10-47-39
Screenshot from 2024-04-18 10-47-25

**Review by abhishekpandit5599 — CHANGES_REQUESTED** [review]
1. The footer is not wrapped in a container
2. Market cards are break
Screenshot from 2024-04-18 10-47-39
Screenshot from 2024-04-18 10-47-25

**Comment by surajaswal-29** [comment]
https://www.awesomescreenshot.com/video/26849194?key=dc9797d000674db732e1c21919a4a3aa

**Review by abhishekpandit5599 — CHANGES_REQUESTED** [review]
1. Footer color take full screen only content wrapped into container
Screenshot from 2024-04-19 11-17-45

**Review by abhishekpandit5599 — CHANGES_REQUESTED** [review]
Fix UI of these screens
Screenshot from 2024-04-19 14-46-31
Screenshot from 2024-04-19 14-45-55

**Review by abhishekpandit5599 — CHANGES_REQUESTED** [review]
UI break on big screens
Screenshot from 2024-04-20 11-02-17
Screenshot from 2024-04-20 11-01-47

**Pull request merged**
